{% set name = "mdsf" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hougesen/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f0a24b8cbc48a9e8e4eb73ba6083083954592940150c632f4bb0bda9fcbdc099

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/hougesen/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Format markdown code blocks using your favorite code formatters.
  dev_url: https://github.com/hougesen/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
