context:
  version: "0.12.1"

package:
  name: mdsf
  version: ${{ version }}

source:
  url: https://github.com/hougesen/mdsf/archive/v${{ version }}.tar.gz
  sha256: c79a131f6e15804c99cff4c9ea0fe917e6b935e3524341255cc323973d2be7fc

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - mdsf --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Format markdown code blocks using your favorite code formatters.
  homepage: https://github.com/hougesen/mdsf
  repository: https://github.com/hougesen/mdsf

extra:
  recipe-maintainers:
    - danielnachun
