context:
  version: 0.3.2

package:
  name: mdsf
  version: ${{ version }}

source:
  url: https://github.com/hougesen/mdsf/archive/v${{ version }}.tar.gz
  sha256: f12bd8db4f7982d639e003496ea5b07fa2c1d3c71f4a1d1899c4556aa85fcbdd

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - mdsf --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Format markdown code blocks using your favorite code formatters.
  homepage: https://github.com/hougesen/mdsf
  repository: https://github.com/hougesen/mdsf

extra:
  recipe-maintainers:
    - danielnachun
